import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Document Manage</title>
        <meta name="description" content="Document management system" />
      </head>
      <body className={inter.className}>
        <div data-theme="cupcake">
          <header className="navbar bg-base-300 text-base-content fixed top-0 w-full">
            <a className="btn btn-ghost normal-case text-xl">Document Manage</a>
          </header>
          <main>
            {children}
          </main>
          <footer className="footer footer-center p-4 bg-base-300 text-base-content">
            <div>
              <p>Copyright © 2024 - All rights reserved by SE 2024 Teaching Group</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
